version: '3'

services:
  web:
    build: ./docker/web
    ports:
    - 80:80
    - 8888:8888
    volumes:
    - ./:/var/www/html
    depends_on:
    - mysql
    - redis

  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci  --default-time-zone=Asia/Tokyo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: haiki_share
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
    ports:
    - 3306:3306
    volumes:
    - mysql-db:/var/lib/mysql
  # redis 5.0.5
  redis:
    image: redis:5.0.5-alpine
    # bind mount
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    command: redis-server

volumes:
  mysql-db:
  redis-data:
